---
title: "analysis"
author: "Maxwel Coura Oliveira"
date: "5/4/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(ggthemes)
library(readxl)
library(drc)
```


```{r}
data <- read_excel("data.xlsx") |> 
  mutate_if(is_character, as_factor) 
```



```{r}
palotina <- data |> 
  filter(location == "palotina")
  
pal_model <- drm(yield ~ dap, herbicida, fct = W1.3(), data = palotina)
```


```{r}
plot(pal_model, ylim = c(0, 3000), log = "")
```


```{r}
summary(pal_model)
broom::tidy(pal_model)
```

```{r}
ED(pal_model, c(2, 5, 10)) 
```


```{r Control prediction, include=FALSE}
newdata <- expand.grid(dap=exp(seq(log(0.5), log(121), length=121)))

newdata1 <- data.frame(herbicida = c("sem pre-emergente"), newdata)
newdata2 <- data.frame(herbicida = c("diclosulan + pyrosaxulfone"), newdata)
newdata3 <- data.frame(herbicida = c("flumioxazin + pyrosaxulfone"), newdata)
newdata4 <- data.frame(herbicida = c("sulfentrazone + diuron"), newdata)

nd=rbind(newdata1, newdata2, newdata3, newdata4)

pm <- predict(pal_model, newdata=nd, interval="confidence")
nd$p <- pm[,1] 
nd$pmin <- pm[,2] 
nd$pmax <- pm[,3] 

palotina$dap0 <- palotina$dap
palotina$dap0[palotina$dap0==0] <- 0.5
```

```{r}
palotina |> 
  ggplot(aes(x = dap, y = yield, color = herbicida, 
             linetype = herbicida,
             pch = herbicida)) +
  geom_line(data=nd, aes(x=dap, y=p), size=1.3) +
  geom_point(alpha = 0.1) +
  theme_base() +
  scale_y_continuous(limits = c(0, 2500)) +
  labs(color = NULL, linetype = NULL, pch = NULL,
       x = "Dias após o plantio",
       y = expression(paste("Produtividade (kg ha "^"-1",")"))) +
  scale_color_brewer(palette = "Set1") +
  guides(color = guide_legend(reverse = TRUE),
         linetype = guide_legend(reverse = TRUE),
         pch = guide_legend(reverse = TRUE)) +
  theme(legend.position = c(0.3, 0.15))

ggsave("palotina.png", width = 6, height = 5)
```





```{r}
curitiba <- data |> 
  filter(location == "curitiba") |> 
  filter(herbicida != "diclosulan + pyrosaxulfone")
  
cur_model <- drm(yield ~ dap, herbicida, fct = l3(), data = curitiba)

cur_model1 <- drm(yield_loss ~ dap, herbicida, fct = W1.4(fixed = c(NA,NA,NA,NA)), 
                  data = curitiba)
```

```{r}
plot(cur_model, log = "")
plot(cur_model1, log = "", ylim = c(0,100))
```
```{r}
broom::tidy(cur_model)
broom::tidy(cur_model1)
```


```{r}
ED(cur_model, c(3974.215), type = "absolute")
```








